linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec
    - gocritic
    - goconst
    - gocognit
    - mnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - goimports

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/
  skip-packages:
    - github.com/go-gl/gl/v2.1/gl

issues:
  exclude-dirs:
    - vendor/
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gosec
        - mnd
    - path: .*\.go
      linters:
        - gosec
      text: "G404: Use of weak random number generator"
      source: "math/rand"

output:
  formats:
    - colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gocyclo:
    min-complexity: 15
  mnd:
    settings:
      mnd:
        checks: assignment,argument,return
  goconst:
    min-len: 2
    min-occurrences: 2 