linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec
    - gocritic
    - goconst
    - gocognit
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - goimports

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gosec
        - gomnd

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gocyclo:
    min-complexity: 15
  gomnd:
    settings:
      mnd:
        checks: assignment,argument,return
  goconst:
    min-len: 2
    min-occurrences: 2 